<a href="https://colab.research.google.com/github/antonysandesh/my-first-repo/blob/master/bitlandProblem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#bitland problem
import numpy as np

a =np.array([[0,0],
            [0,1],
            [2,3],
            [4,4],
            [3,2]])
b = np.array([[0,4],
            [1,0],
            [2,4],
            [3,1]])

In [2]:
print(a)
print(b)

[[0 0]
 [0 1]
 [2 3]
 [4 4]
 [3 2]]
[[0 4]
 [1 0]
 [2 4]
 [3 1]]


In [3]:
from scipy.spatial.distance import cdist

c = cdist(a,b)
print(c)

[[4.         1.         4.47213595 3.16227766]
 [3.         1.41421356 3.60555128 3.        ]
 [2.23606798 3.16227766 1.         2.23606798]
 [4.         5.         2.         3.16227766]
 [3.60555128 2.82842712 2.23606798 1.        ]]


In [4]:
#1-1
a[:,0].argmax()

3

In [5]:
#1-2
a[:,1].argmax()

3

In [6]:
#1-3
cdist(a,[[0,0]]).argmax(axis=0)

array([3])

In [7]:
#1-4
b.argmax(axis=0)

array([3, 0])

In [8]:
#1-5
cdist(b,[[0,0]]).argmax(axis=0)

array([2])

In [9]:
#1-6
cdist(b,[[0,0]]).max(axis=0)

array([4.47213595])

In [10]:
#2-1
c[0,0]

4.0

In [11]:
#2-2
c[2]

array([2.23606798, 3.16227766, 1.        , 2.23606798])

In [12]:
#2-3
c

array([[4.        , 1.        , 4.47213595, 3.16227766],
       [3.        , 1.41421356, 3.60555128, 3.        ],
       [2.23606798, 3.16227766, 1.        , 2.23606798],
       [4.        , 5.        , 2.        , 3.16227766],
       [3.60555128, 2.82842712, 2.23606798, 1.        ]])

In [13]:
#3-1
c[2].argmin()

2

In [14]:
#3-2
c.argmin(axis=1)

array([1, 1, 2, 2, 3])

In [15]:
#3-3
c.argmax(axis=1)

array([2, 2, 1, 1, 0])

In [16]:
#3-4
c.min(axis=1)

array([1.        , 1.41421356, 1.        , 2.        , 1.        ])

In [17]:
#4-1
c[:,1].argmin(axis=0)


0

In [18]:
#4-2
c.argmin(axis=0)

array([2, 0, 2, 4])

In [19]:
4-3
c.min(axis=0)

array([2.23606798, 1.        , 1.        , 1.        ])

In [20]:
#5-1
c[2].sum()

8.63441361516796

In [21]:
#5-2
c.sum(axis=1)

array([12.63441362, 11.01976484,  8.63441362, 14.16227766,  9.67004638])

In [22]:
#5-3
c[:,[0,1,3]].sum(axis=1)

array([ 8.16227766,  7.41421356,  7.63441362, 12.16227766,  7.4339784 ])

In [23]:
#5-4
c[:,[1,3]].sum(axis=1)

array([4.16227766, 4.41421356, 5.39834564, 8.16227766, 3.82842712])

In [24]:
#or other way to remove the super markets 
c.sum(axis=1) - c[:,[0,1]].sum(axis=1)

array([7.63441362, 6.60555128, 3.23606798, 5.16227766, 3.23606798])

In [25]:
#6-1
c.mean(axis=1)

array([3.1586034 , 2.75494121, 2.1586034 , 3.54056942, 2.41751159])

In [26]:
#6-2
c.mean(axis=0)

array([3.36832385, 2.68098367, 2.66275104, 2.51212466])

In [27]:
#7-1
c_int = c.astype(int)
print(c)
print(c_int)
print(c == c_int)
print((c == c_int).sum())


[[4.         1.         4.47213595 3.16227766]
 [3.         1.41421356 3.60555128 3.        ]
 [2.23606798 3.16227766 1.         2.23606798]
 [4.         5.         2.         3.16227766]
 [3.60555128 2.82842712 2.23606798 1.        ]]
[[4 1 4 3]
 [3 1 3 3]
 [2 3 1 2]
 [4 5 2 3]
 [3 2 2 1]]
[[ True  True False False]
 [ True False False  True]
 [False False  True False]
 [ True  True  True False]
 [False False False  True]]
9


In [28]:
#7-2
(c == c_int).sum(axis=0).argmax()

0

In [29]:
#7-3
mask = (c == c_int)
print(mask)
print(mask * c_int )
print((mask * c_int).sum(axis=1))
 

[[ True  True False False]
 [ True False False  True]
 [False False  True False]
 [ True  True  True False]
 [False False False  True]]
[[4 1 0 0]
 [3 0 0 3]
 [0 0 1 0]
 [4 5 2 0]
 [0 0 0 1]]
[ 5  6  1 11  1]


In [30]:
#7-4
c.sum(axis=1) - (mask*c).sum(axis=1)


array([7.63441362, 5.01976484, 7.63441362, 3.16227766, 8.67004638])

In [31]:
# 8-1
c[:,0].argmax()

0

In [32]:
#8-2
c.min(axis=1).argmax()

3

In [33]:
#8-3
c.min(axis=1)

array([1.        , 1.41421356, 1.        , 2.        , 1.        ])

In [34]:
#8-4
c.min(axis=0)

array([2.23606798, 1.        , 1.        , 1.        ])

In [35]:
#9-1
c.sum(axis=1).argmax()

3

In [36]:
c.sum(axis=1).argmin()

2

In [37]:
#9-2
 c.sum(axis=1).argsort()

array([2, 4, 1, 0, 3])

In [38]:
#10
x = np.where(c < 4)
print(x)

(array([0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 4, 4, 4, 4]), array([1, 3, 0, 1, 2, 3, 0, 1, 2, 3, 2, 3, 0, 1, 2, 3]))


In [39]:
list(zip(x[0],x[1]))

[(0, 1),
 (0, 3),
 (1, 0),
 (1, 1),
 (1, 2),
 (1, 3),
 (2, 0),
 (2, 1),
 (2, 2),
 (2, 3),
 (3, 2),
 (3, 3),
 (4, 0),
 (4, 1),
 (4, 2),
 (4, 3)]