<a href="https://colab.research.google.com/github/antonysandesh/my-first-repo/blob/master/marathonProblem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#Marathon problem
import numpy as np

a = np.array([[2,3,5,4],
             [3,5,2,1],
             [7,6,2,1],
             [3,2,4,5],
             [2,2,2,2]])

b = np.array([3,5,2,3])



In [3]:
#1
print(a.dot(b))
print(a.dot(b).argmax())
print(a.dot(b).argmin())

[43 41 58 42 26]
2
4


In [4]:
print(a[0].dot(b))
print(a[1].dot(b))
print(a[2].dot(b))
print(a[3].dot(b))
print(a[4].dot(b))



43
41
58
42
26


In [5]:
#3
print(a[1,0:].dot(b))

41


In [6]:

c = a * b

print(c)

[[ 6 15 10 12]
 [ 9 25  4  3]
 [21 30  4  3]
 [ 9 10  8 15]
 [ 6 10  4  6]]


In [7]:
c.sum(axis=1)

array([43, 41, 58, 42, 26])

In [8]:
c.sum(axis=1).argmax()


2

In [9]:
c.argmax(axis=0)

array([2, 2, 0, 3])

In [10]:

c[1].sum()

41

In [11]:
#4-1
c[2,:3].sum()

55

In [12]:
#4-2
c[3,[0,2,3]].sum()

32

In [13]:
#4-3
c[2:,[0,2,3]].sum(axis=1)

array([28, 32, 16])

In [14]:
#5
print(c[:,1]>c[0,1])
print((c[:,1]>c[0,1]).sum())

[False  True  True False False]
2


In [15]:
#6
e = c[:,[0,1,3]].sum(axis=1)
e>e[0]
print((e>e[0]).sum())


3


In [16]:
#7-1
c[0].sum()-c[4].sum()

17

In [17]:
#7-2
c[:,0].mean()

10.2

In [18]:
#7-3
c[0].mean()

10.75

In [19]:
#7-4
c.mean(axis=1)

array([10.75, 10.25, 14.5 , 10.5 ,  6.5 ])

In [20]:
#8
c.sum(axis=0).argmax()


1

In [21]:
#8
c.sum(axis=0).argmin()


2

In [22]:
#9
b.argmax()

1

In [23]:
#10
a[:,3].mean()

2.6