<a href="https://colab.research.google.com/github/antonysandesh/my-first-repo/blob/master/matrixmultiplication%2Cetc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
# Matrix multiplication using python

def Multiply(m1,m2):
    Rows = len(m1)
    Col = len(m2[0])
    MatrixMul = [[0] * Col for i in range(Rows)]
    for i in range(Rows):
        for j in range(Col):
            for k in range(len(m2)):
                MatrixMul[i][j]+=m1[i][k]*m2[k][j]
    return MatrixMul    
m1 = [[2,3,2],[4,7,8]]
m2 = [[3,4,5,8,7],[6,8,2,1,4],[3,6,7,4,6]]
print(Multiply(m1,m2))


[[30, 44, 30, 27, 38], [78, 120, 90, 71, 104]]


In [19]:
#Matrix multiplication using numpy
import numpy as np
def Multiply(m1,m2):
    res = np.dot(m1,m2)
    return res
m1 = [[2,3,2],[4,7,8]]
m2 = [[3,4,5,8,7],[6,8,2,1,4],[3,6,7,4,6]]
Result = Multiply(m1,m2)
print(Result)

[[ 30  44  30  27  38]
 [ 78 120  90  71 104]]


In [21]:
#Removing duplicate elements from the list
def Removedup(list):
    d = []
    print("The original list is:",list)
    for i in list:
        if i not in d:
            d.append(i)
    return d
list = [1,3,4,5,6,7,3,4,2,6,8,5,3,8]
result = Removedup(list)
print("list after removing duplicates:",result)

The original list is: [1, 3, 4, 5, 6, 7, 3, 4, 2, 6, 8, 5, 3, 8]
list after removing duplicates: [1, 3, 4, 5, 6, 7, 2, 8]


In [22]:
# fibinocci series
def fibinocci(n):
    a = 0
    b = 1
    if n < 0:
        print("enter a positive number")
    else:
        print(a,end="  ")
        for i in range(2,n+1):
            temp = a + b
            a = b
            b = temp
            print(temp,end= '  ')
fibinocci(int(input("enter a number for fibinocci==>")))

enter a number for fibinocci==>20
0  1  2  3  5  8  13  21  34  55  89  144  233  377  610  987  1597  2584  4181  6765  

In [49]:
#Reshape of matrix using numpy
import numpy as np 
           
a = np.array([64, 1,3,4,5,1]) 
print(a)

b = a.reshape(2,3)
print(b)

[64  1  3  4  5  1]
[[64  1  3]
 [ 4  5  1]]
